2018/08/02 23:42:23 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "gii/carreras". in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/carreras')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiiapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiiapp/index.php?r=gii/carreras
---
2018/08/09 23:30:39 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "carreras". in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('carreras')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiiapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiiapp/index.php/carreras
---
2018/08/22 21:12:40 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
 in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiiapp\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiiapp/index.php/gii/model/index
HTTP_REFERER=http://localhost/yiiapp/index.php/gii/default/index
---
2018/08/22 21:13:36 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
 in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiiapp\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiiapp/index.php/gii/model/index
HTTP_REFERER=http://localhost/yiiapp/index.php/gii/default/index
---
2018/08/22 21:18:19 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'limesurvey.survey' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `survey`.
in C:\xampp\htdocs\yiiapp\index.php (13)
2018/08/22 23:38:12 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "survey". in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('survey')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiiapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiiapp/index.php/survey
---
2018/08/22 23:38:15 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "surveys". in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('surveys')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiiapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiiapp/index.php/surveys
---
2018/08/22 23:38:29 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "survey". in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('survey')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiiapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiiapp/index.php/survey
---
2018/08/22 23:38:33 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "surveys". in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('surveys')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiiapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiiapp/index.php/surveys
---
2018/08/22 23:41:03 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "surveys164846". in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('surveys164846')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiiapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiiapp/index.php/surveys164846
---
2018/08/22 23:41:09 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "surveys_164846". in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('surveys_164846')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiiapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiiapp/index.php/surveys_164846
---
2018/08/23 00:11:54 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "survey". in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('survey')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiiapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiiapp/index.php/survey
---
